---
name: Selenium Tests

"on": ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Install Firefox dependencies (for headless mode)
        run: |
          sudo apt-get update
          # xvfb provides a virtual display buffer, often needed for headless browsers
          # libgtk-3-0, libdbus-glib-1-2 are common dependencies for Firefox
          sudo apt-get install -y xvfb libgtk-3-0 libdbus-glib-1-2

      - name: Set up Firefox and Geckodriver
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest"

      - name: Run Firefox version check
        run: firefox --version

      - name: Run Selenium Tests with Pytest
        run: pytest your_test_file.py
